version: 2.1
jobs:
  trigger:
    docker:
      - image: alpine:3.9
    steps:
      - run:
          command: echo "Build And Push Docker Image"
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t salvax86/tools:${CIRCLE_BRANCH}
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            docker push salvax86/tools:${CIRCLE_BRANCH}
workflows:
  version: 2
  init_plan_apply:
    jobs:
      - trigger:
          type: approval
      - build:
          requires:
            - trigger

