version: 2.1
jobs:
  trigger:
    docker:
      - image: alpine:3.9
    steps:
      - run:
          command: echo "Build And Push Docker Image"
  build:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install GOSS
          command: |
            mkdir ~/bin
            export GOSS_DST=~/bin
            export PATH=$PATH:~/bin
            curl -fsSL https://goss.rocks/install | sh
            goss -version
      - run:
          name: Build and Test docker image
          command: |
            export PATH=$PATH:~/bin
            export GOSS_FILES_STRATEGY=cp
            docker build -t salvax86/tools:${CIRCLE_BRANCH} --build-arg ansible_version=2.8.0 --build-arg terraform_version=0.12.0 --build-arg awscli_version=1.16.164 .
            GOSS_FILES_PATH=test dgoss run -it salvax86/tools:${CIRCLE_BRANCH}
      - store_test_results:
          path: reports
workflows:
  version: 2
  init_plan_apply:
    jobs:
      - trigger:
          type: approval
      - build:
          requires:
            - trigger

